name: 'Config Entity Example'
type: module
description: 'Demonstrates how to create a config entity type.'
package: Example modules
core_version_requirement: ^10.3
dependencies:
  - examples:examples

# Information added by Drupal.org packaging script on 2024-08-28
version: '4.0.3'
project: 'examples'
datestamp: 1724874136
