contact_layout.settings:
  type: config_object
  label: Contact Layout List Content Type Settings
  mapping:
    allowed_types:
      type: sequence
      label: Content types the Contact Layout can display on
      sequence:
        type: string
        label: Content type
